# Supabase credentials from your dashboard
SUPABASE_URL = "https://evpifmjjrdofqdhdssbc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cGlmbWpqcmRvZnFkaGRzc2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxODkwNjksImV4cCI6MjEwMzc2NTA2OX0.i0eSwRCmBQDdmFcBwiLmnT2E9BPhGqYf9OjjZneQYs0"
